# Generated by Django 4.2.30 on 2026-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('nit', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIT / Documento')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega', models.DateField()),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Anticipo pagado', 'Anticipo pagado'), ('Pagado completo', 'Pagado completo')], default='Pendiente', max_length=50)),
                ('estado_orden', models.CharField(choices=[('En proceso', 'En proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='En proceso', max_length=50)),
                ('especificaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('linea', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('operario', 'Operario'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
